services: docker
before_install:
- openssl aes-256-cbc -K $encrypted_c52cc6e40103_key -iv $encrypted_c52cc6e40103_iv -in .dropbox_uploader.enc -out ~/.dropbox_uploader -d
script:
- wget https://raw.githubusercontent.com/blang/latex-docker/master/latexdockercmd.sh
- chmod +x latexdockercmd.sh
- ./latexdockercmd.sh latexmk -pdf -outdir=./_build CV.tex
- ./dropbox_uploader.sh upload _build/patrick_roddy_cv.pdf ${TRAVIS_BRANCH}/patrick_roddy_cv-latest.pdf
- ./dropbox_uploader.sh upload _build/patrick_roddy_cv.pdf ${TRAVIS_BRANCH}/patrick_roddy_cv-${TRAVIS_JOB_NUMBER}.pdf