name: Build LaTeX

on: [push, pull_request]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: checkout source
              uses: actions/checkout@v2

            - name: Build PDF
              uses: xu-cheng/latex-action@v2
              with:
                  root_file: |
                      CV.tex

            - name: Set up Dropbox
              run: |
                  echo "CONFIGFILE_VERSION=$CONFIGFILE_VERSION" > ~/.dropbox_uploader
                  echo "OAUTH_APP_KEY=$OAUTH_APP_KEY" >> ~/.dropbox_uploader
                  echo "OAUTH_APP_SECRET=$OAUTH_APP_SECRET" >> ~/.dropbox_uploader
                  echo "OAUTH_REFRESH_TOKEN=$OAUTH_REFRESH_TOKEN" >> ~/.dropbox_uploader
              env:
                  CONFIGFILE_VERSION: ${{secrets.CONFIGFILE_VERSION}}
                  OAUTH_APP_KEY: ${{secrets.OAUTH_APP_KEY}}
                  OAUTH_APP_SECRET: ${{secrets.OAUTH_APP_SECRET}}
                  OAUTH_REFRESH_TOKEN: ${{secrets.OAUTH_REFRESH_TOKEN}}

            - name: Upload PDFs
              run: |
                  ./dropbox_uploader.sh upload CV.pdf patrick_roddy_cv.pdf
